###EMPLOYEE BASIC ROUTES TESTS

###FIND ALL EMPLOYEES
GET http://localhost:3000/employee/
Accept: application/json
###

###CREATE EMPLOYEE
POST http://localhost:3000/employee/
Content-Type: application/json

{
    "department": "Supply Chain",
    "email": "pedro.castro@empresa.com.br",
    "emp_username": "Pcastro",
    "emp_password": "Password123",
    "name": "Pedro Castro"

}
###

###DELETE EMPLOYEE (IN THIS ONE YOU HAVE TO PUT THE ID GENERATED IN YOUR DB)
DELETE http://localhost:3000/employee/{coordinatorId}
Accept: application/json
###

###UPDATE EMPLOYEE (IN THIS ONE YOU HAVE TO PUT THE ID GENERATED IN YOUR DB)
PUT http://localhost:3000/employee/{coordinatorId}
Content-Type: application/json

{
    "department": "Compliance",
    "name": "Pedro Costa Júnior",
    "email": "pedro.costa@empresa.com.br",
    "emp_password": "Password43452",
    "emp_username": "Pcosta"
}

###

###COORDINATORS BASIC ROUTES TESTS

###FIND ALL COORDINATORS
GET http://localhost:3000/coordinator/
Accept: application/json

###

###CREATE COORDINATOR
POST http://localhost:3000/coordinator
Content-Type: application/json

{
    "department": "Compliance",
    "email": "j.caraderato@email.com.br",
    "coord_username": "Jrato12",
    "coord_password": "Password1234",
    "name": "João Caraderato"

} 
###

###DELETE COORDINATOR (IN THIS ONE YOU HAVE TO PUT THE ID GENERATED IN YOUR DB)
DELETE http://localhost:3000/coordinator/
Accept: application/json
###

###UPDATE COORDINATOR (IN THIS ONE YOU HAVE TO PUT THE ID GENERATED IN YOUR DB)
PUT http://localhost:3000/coordinator/{coordinatorId}
Content-Type: application/json
{
    "department": "Compliance",
    "nome": "João Caraderato 2",

}
###

###TASKS BASIC ROUTES TESTS


###FIND ALL TASKS
GET http://localhost:3000/task/
Accept: application/json
###

###CREATE TASK
POST http://localhost:3000/task/
Content-Type: application/json

{
    "task_description": "Compra de chave sextavada",
    "task_type": "Compra",
    "init_date": "2025-06-08",
    "due_date": "2025-06-29"
}
###

###DELETE TASK (IN THIS ONE YOU HAVE TO PUT THE ID GENERATED IN YOUR DB)
DELETE http://localhost:3000/task/c
Accept: application/json
###

###UPDATE TASK (IN THIS ONE YOU HAVE TO PUT THE ID GENERATED IN YOUR DB)
PUT http://localhost:3000/task/{task_id}
Content-Type: application/json

{
    "emp_id": "b01d4a71-69c4-4fc4-8ee3-c6593fcf6744",
    "coord_id": "9646d7da-4e17-4222-94d9-b0f4f845a0f8",
    "task_description": "Descrição de tarefa atualizada",
    "init_date": "2025-06-20",
    "due_date": "2025-06-29"
}
###